---
name: CI

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run lint
      - run: bun run check
      - run: bun run test

      - run: bun run build

      # Ensure that we produced a dist folder
      - run: test -f build/index.html

      - name: Deploy
        if: github.ref == 'refs/heads/boss'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          publish_dir: ./build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: ${{ github.event.head_commit.message }}
